[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    tzapu/WiFiManager
    me-no-dev/AsyncTCP
    mathieucarbou/ESP Async WebServer
monitor_speed = 115200
board_build.flash_mode = dio
